### ISSUE TITLE
Error while running "python bootstrap.py login".

### ISSUE THREAD

**Issue by Anthpect101** [solero/houdini#104]
Greetings.
I have encountered this error while running "python bootstrap.py login":
Traceback (most recent call last):
File "/home/anthpect/houdini/bootstrap.py", line 141, in
asyncio.run(factory_instance.start())
File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
File "/home/anthpect/houdini/houdini/houdini.py", line 130, in start
await self.db.set_bind('postgresql://{}:{}@{}/{}'.format(
File "/home/anthpect/.local/lib/python3.12/site-packages/gino/api.py", line 417, in set_bind
bind = await create_engine(bind, loop=loop, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/gino/strategies.py", line 55, in create
pool = await dialect.init_pool(u, loop, pool_class=pool_class)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool
return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/gino/dialects/asyncpg.py", line 218, in _init
self.pool = await asyncpg.create_pool(**args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/pool.py", line 418, in async__init
await self._initialize()
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/pool.py", line 445, in _initialize
await first_ch.connect()
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/pool.py", line 132, in connect
self._con = await self._pool._get_new_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
con = await self._connect(
^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
return await connect_utils._connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
raise last_error or exceptions.TargetServerAttributeNotMatched(
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
conn = await _connect_addr(
^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
return await __connect_addr(params, True, *args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
tr, pr = await connector
^^^^^^^^^^^^^^^
File "/home/anthpect/.local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
tr, pr = await loop.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 2043, in create_connection
File "uvloop/loop.pyx", line 2020, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

Server Info:
Manjaro Linux x86_64

**Comment by AllinolCP** [comment]
Not a bug, Postgresql is down
