### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by rodrigopereiraa** [Solero/Houdini#17]
[1] 24149
Traceback (most recent call last):
  File "World.py", line 3, in <module>
    server = HoudiniFactory(server="Wind")
  File "/home/rodrigopereira/houdini/Houdini/HoudiniFactory.py", line 60, in __init__
    maxBytes=2097152, backupCount=3, encoding="utf-8")
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 945, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: '/home/rodrigopereira/houdini/logs/wind.log'

P.S: please leave your discord

**Comment by Spydar007** [comment]
**GitHub issues are not for support.**

This is **not** an issue with Houdini and is instead _a problem with your local system_ as the plain English error tells you.

Join the Solero Discord for support.

**Comment by ketnipz** [comment]
As @Spydar007 says this is not an issue with Houdini, you may ask for help at the [Solero Discord](https://dicsord.solero.me).

Issue closed.
