### ISSUE TITLE
Houdini does not start

### ISSUE THREAD

**Issue by Pajamaland** [solero/houdini#60]
**Describe the bug**
Houdini refuses to start, falls back to terminal on 

**Client Type:**
Vanilla(?), latest git

**To Reproduce**
Unsure if this is a specific issue with my machine, but all I did was git clone houdini, install requirements using pip and run the command "python bootstrap.py login"

**Install Method**
Git clone

**Expected behavior**
I expected the server to start running.

**Log**
Traceback (most recent call last):
  File "bootstrap.py", line 141, in <module>
    asyncio.run(factory_instance.start())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/tux/houdini/houdini/houdini.py", line 130, in start
    await self.db.set_bind('postgresql://{}:{}@{}/{}'.format(
  File "/home/tux/.local/lib/python3.8/site-packages/gino/api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/tux/.local/lib/python3.8/site-packages/gino/strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "/home/tux/.local/lib/python3.8/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "/home/tux/.local/lib/python3.8/site-packages/gino/dialects/asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 426, in _initialize
    await first_ch.connect()
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/connection.py", line 1718, in connect
    return await connect_utils._connect(
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 674, in _connect
    raise last_error
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 663, in _connect
    con = await _connect_addr(
  File "/home/tux/.local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 632, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1974, in create_connection
  File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

**Server Info:**
Ubuntu 20.04

**Comment by AllinolCP** [comment]
It is clearly said in the logs. you didn't turn on postgresql please turn it on first then report back
Thank You

**Comment by Pajamaland** [comment]
> It is clearly said in the logs. you didn't turn on postgresql please turn it on first then report back
> Thank You

I have installed and enabled postgresql, and now I'm presented with a new error. 

asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

The user postgres does not have a password. Houdini currently lacks documentation. Is there anything I should be doing to configure stuff? I was just told to run the py script in the documentation, or lack-there-of.

**Comment by Pajamaland** [comment]
Running on Windows, I now get this:

2020-08-26 14:57:18,589 [INFO ]  Booting Houdini
Traceback (most recent call last):
  File "bootstrap.py", line 141, in <module>
    asyncio.run(factory_instance.start())
  File "C:\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\hooey\houdini\houdini\houdini.py", line 137, in start
    self.redis = await aioredis.create_redis_pool('redis://{}:{}'.format(
  File "C:\Python38\lib\site-packages\aioredis\commands\__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "C:\Python38\lib\site-packages\aioredis\pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "C:\Python38\lib\site-packages\aioredis\pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "C:\Python38\lib\site-packages\aioredis\connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "C:\Python38\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Python38\lib\site-packages\aioredis\stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "C:\Python38\lib\asyncio\base_events.py", line 1030, in create_connection
    raise exceptions[0]
  File "C:\Python38\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "C:\Python38\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Python38\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Python38\lib\asyncio\windows_events.py", line 595, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E93B0C88B0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

**Comment by AllinolCP** [comment]
> Running on Windows, I now get this:
> 
> 2020-08-26 14:57:18,589 [INFO ] Booting Houdini
> Traceback (most recent call last):
> File "bootstrap.py", line 141, in
> asyncio.run(factory_instance.start())
> File "C:\Python38\lib\asyncio\runners.py", line 43, in run
> return loop.run_until_complete(main)
> File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
> return future.result()
> File "C:\Users\hooey\houdini\houdini\houdini.py", line 137, in start
> self.redis = await aioredis.create_redis_pool('redis://{}:{}'.format(
> File "C:\Python38\lib\site-packages\aioredis\commands__init__.py", line 188, in create_redis_pool
> pool = await create_pool(address, db=db,
> File "C:\Python38\lib\site-packages\aioredis\pool.py", line 58, in create_pool
> await pool._fill_free(override_min=False)
> File "C:\Python38\lib\site-packages\aioredis\pool.py", line 383, in _fill_free
> conn = await self._create_new_connection(self._address)
> File "C:\Python38\lib\site-packages\aioredis\connection.py", line 111, in create_connection
> reader, writer = await asyncio.wait_for(open_connection(
> File "C:\Python38\lib\asyncio\tasks.py", line 455, in wait_for
> return await fut
> File "C:\Python38\lib\site-packages\aioredis\stream.py", line 23, in open_connection
> transport, _ = await get_event_loop().create_connection(
> File "C:\Python38\lib\asyncio\base_events.py", line 1030, in create_connection
> raise exceptions[0]
> File "C:\Python38\lib\asyncio\base_events.py", line 1010, in create_connection
> sock = await self._connect_sock(
> File "C:\Python38\lib\asyncio\base_events.py", line 924, in _connect_sock
> await self.sock_connect(sock, address)
> File "C:\Python38\lib\asyncio\proactor_events.py", line 702, in sock_connect
> return await self._proactor.connect(sock, address)
> File "C:\Python38\lib\asyncio\windows_events.py", line 808, in _poll
> value = callback(transferred, key, ov)
> File "C:\Python38\lib\asyncio\windows_events.py", line 595, in finish_connect
> ov.getresult()
> ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x000001E93B0C88B0>
> Traceback (most recent call last):
> File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in **del**
> File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
> File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
> File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
> RuntimeError: Event loop is closed

install redis, Its on readme.md

**Comment by Pajamaland** [comment]
I installed the requirements through pip. Unless you're referring to something I can't find.

**Comment by AllinolCP** [comment]
correction* the redis is not on readme, please join the discord to get support

**Comment by DiamondFiire** [comment]
This isn't an issue sweetie...

**Comment by Pajamaland** [comment]
> This isn't an issue sweetie...

It might not be. But I'm a newbie when it comes to stuff like PostgreSQL, so I do appreciate the support more than sarcasm :)

**Comment by AllinolCP** [comment]
if you want support join the discord

**Comment by Pajamaland** [comment]
> if you want support join the discord

Yes, I will. I started this issue because that's what it appeared to be to me, an issue.

**Comment by AllinolCP** [comment]
_this_ _is_ _more_ _like_ _a_ _user_ _issue_ _but_ _ok_

**Comment by DiamondFiire** [comment]
This is a you problem, not a Houdini problem...
