### ISSUE TITLE
this came up when preforming "python bootstrap.py login" (and I did run as admin)

### ISSUE THREAD

**Issue by Fern-Leaves** [solero/houdini#75]
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

**Comment by AllinolCP** [comment]
have you installed PostgreSQL and Redis?

**Comment by DiamondFiire** [comment]
How exactly is this a bug

**Comment by Fern-Leaves** [comment]
I did
pip install -r requirements.txt

**Comment by Fern-Leaves** [comment]
> How exactly is this a bug

I never said it was a bug I submitted it as an "issue"

**Comment by DiamondFiire** [comment]
And the difference being?

**Comment by Fern-Leaves** [comment]
> And the difference being?

A bug is an issue with the code, an issue without any prefix is just something that went wrong. also this might be something wrong with the code because I have installed everything in requirments.txt, updated python to the latest version, and let python through the firewall; I don't really see what else could be causing this.
`cd C:\houdini
bootstrap.py login
pause`
is the code in the bat file I am using to run Houdini

**Comment by Fern-Leaves** [comment]
### Here is the full log (windows username replaced with --- for privacy)

C:\houdini>cd C:\houdini

C:\houdini>bootstrap.py login
Traceback (most recent call last):
  File "C:\houdini\bootstrap.py", line 141, in <module>
    asyncio.run(factory_instance.start())
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\houdini\houdini\houdini.py", line 130, in start
    await self.db.set_bind('postgresql://{}:{}@{}/{}'.format(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 407, in _async__init__
    await self._initialize()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 435, in _initialize
    await first_ch.connect()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 127, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 477, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connection.py", line 1981, in connect
    return await connect_utils._connect(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 748, in _connect
    raise last_error
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 732, in _connect
    con = await _connect_addr(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 632, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 676, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\compat.py", line 103, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 542, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1061, in create_connection
    raise exceptions[0]
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

C:\houdini>pause
Press any key to continue . . .

**Comment by AllinolCP** [comment]
> have you installed PostgreSQL and Redis?
please refer to this

**Comment by AllinolCP** [comment]
It needs PostgreSQL for the player data and Redis for temporary data

**Comment by Fern-Leaves** [comment]
> It needs PostgreSQL for the player data and Redis for temporary data

I have installed those now, but why didn't it say to install them in [readme.md](https://github.com/solero/houdini/blob/master/README.md), also I'm getting this error now

C:\houdini>cd C:\houdini

C:\houdini>bootstrap.py login
Traceback (most recent call last):
  File "C:\houdini\bootstrap.py", line 141, in <module>
    asyncio.run(factory_instance.start())
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\houdini\houdini\houdini.py", line 130, in start
    await self.db.set_bind('postgresql://{}:{}@{}/{}'.format(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 407, in _async__init__
    await self._initialize()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 435, in _initialize
    await first_ch.connect()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 127, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\pool.py", line 477, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connection.py", line 1981, in connect
    return await connect_utils._connect(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 732, in _connect
    con = await _connect_addr(
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 632, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\connect_utils.py", line 682, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncpg\compat.py", line 103, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "C:\Users\---\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

C:\houdini>pause
Press any key to continue . . .

**Comment by AllinolCP** [comment]
> asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

please learn how to read,
Thank You

**Comment by Fern-Leaves** [comment]
And where was I supposed to put in a password?

**Comment by Fern-Leaves** [comment]
> > asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"
> 
> please learn how to read,
> Thank You

I know that, but where on earth was I supposed to input a password? I know what password it wants, (the one I put in when setting up PostgreSQL) but it never asked for a password, that was the entire log if the command prompt window it never asked for a password, how could I have put in a password if it never gave me the opportunity?

**Comment by AllinolCP** [comment]
you can either edit it by opening bootstrap.py 
or add --database-password <password> when starting houdini,
Thank You

**Comment by Fern-Leaves** [comment]
C:\houdini>cd C:\houdini

C:\houdini>bootstrap.py login --database-password (my password was here)
2021-07-08 11:34:10,574 [INFO ]  Booting Houdini
Traceback (most recent call last):
  File "C:\houdini\bootstrap.py", line 141, in <module>
    asyncio.run(factory_instance.start())
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\houdini\houdini\houdini.py", line 137, in start
    self.redis = await aioredis.create_redis_pool('redis://{}:{}'.format(
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\site-packages\aioredis\commands\__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\site-packages\aioredis\pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\site-packages\aioredis\pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\site-packages\aioredis\connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\site-packages\aioredis\stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1061, in create_connection
    raise exceptions[0]
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014DC99720D0>
Traceback (most recent call last):
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\(my username was here)\(my username was here)\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

C:\houdini>pause
Press any key to continue . . .

**Comment by AllinolCP** [comment]
looks like redis is not running

**Comment by DiamondFiire** [comment]
> looks like redis is not running

ok I wil start redis
